name: My Windows Build

on:
  workflow_dispatch:


jobs:
  proxspace:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      PATH: C:/ProxSpace/msys2/mingw64/bin;C:/ProxSpace/msys2/usr/local/bin;C:/ProxSpace/msys2/usr/bin;C:/ProxSpace/msys2/bin
      MSYSTEM: MINGW64
      PYTHONHOME: /mingw64

    steps:
      - name: ProxSpace download
        run: Invoke-WebRequest "https://github.com/Gator96100/ProxSpace/archive/master.zip" -outfile "C:\proxspace.zip" -Passthru

      - name: ProxSpace extract
        run: Expand-Archive -LiteralPath "C:\proxspace.zip" -DestinationPath "C:\"

      - name: ProxSpace delete zip
        run: Remove-Item "C:\proxspace.zip"

      - name: ProxSpace rename folder
        run: Get-ChildItem -Path "C:\ProxSpace-*" | Rename-Item -NewName (Split-Path C:\ProxSpace -Leaf)

      - name: ProxSpace version
        run: |
          $psversion = (Select-String -Pattern 'PSVERSION=' -SimpleMatch -Path "C:\ProxSpace\setup\09-proxspace_setup.post").Line.Split("""")[1]
          Write-Host "ProxSpace version: $psversion"

      - name: ProxSpace initial startup
        working-directory: C:\ProxSpace
        run: ./runme64.bat -c "exit"

      - uses: actions/checkout@v4
        # with:
        #   ref: v4.20469

      - name: make clean
        run: make clean

      - name: Build
        run: make -j $([System.Environment]::ProcessorCount + 1) V=1

      - name: Test
        run: make check

      - name: make clean
        run: make clean

      - name: Build btaddon
        run: make -j $([System.Environment]::ProcessorCount + 1) V=1 PLATFORM_EXTRAS=BTADDON

      - name: Test btaddon
        run: make check

      - name: make clean
        run: make clean

      - name: Prepare cmake build folders
        run: |
          mkdir -p client/build
          ln -s ../cmdscripts client/build/
          ln -s ../luascripts client/build/
          ln -s ../pyscripts client/build/
          ln -s ../lualibs client/build/

      - name: Initiate cmake environment
        run: cmake -G"MSYS Makefiles" ..
        working-directory: client/build/

      - name: Build cmake
        run: make -j $([System.Environment]::ProcessorCount + 1) VERBOSE=1
        working-directory: client/build/

      - name: Test cmake
        run: make client/check CHECKARGS="--clientbin ./client/build/proxmark3"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: client/build/
